spring.application.name=distributed_last-write-wins

spring.datasource.url=jdbc:sqlite:data/node-${server.port}.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8080

node.id=0
node.url=http://localhost:${server.port}
cluster.replication-token=dev-replication-token

# Logging
logging.level.com.example.distributed_last_write_wins=INFO
